# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_method.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: cytonorm_all_controls_to_goal
# A relatively short label, used when rendering visualisations (required)
label: CytoNorm (all-controls, to-goal)
# A one sentence summary of how this method works (required). Used when 
# rendering summary tables.
summary: CytoNorm run with all control samples, correcting to a goal batch.
# A multi-line description of how this component works (required). Used
# when rendering reference documentation.
description: |
  CytoNorm corrects batch effects by using reference control samples (aliquots of one sample, 
  technical replicates) included with each batch. 
  It clusters cells using FlowSOM, then trains a model on the control samples to learn how marker 
  expression distributions differ across batches for each population.
  It then uses splines to align these distributions to a common reference (either a midpoint
  derived from all batches or to a single batch).

  Here, we run CytoNorm using all control samples available, aligning the batches to batch 1.

  The parameter nQ, which specifies the number of quantiles used when computing the splines
  is varied linearly between value of 80-120, with default set to 99 following the default value provided by CytoNorm.
  Clustering was performed by FlowSOM.
  The number of cells clustered by FlowSOM is set to be number of cells in the smallest
  control samples or 1,000,000, whichever is the smaller, multiplied by how many control samples
  there are in the data.
  The size of the SOM grid is varied linearly between value of 6-16, with default set to 15
  following the default value provided by CytoNorm.
  The number of metaclusters is varied linearly between value of 8-20, with default set to 10
  following the default value provided by CytoNorm.

references:
  doi: 
    - 10.1002/cyto.a.23904
links:
  # URL to the documentation for this method (required).
  documentation: https://github.com/saeyslab/CytoNorm
  # URL to the code repository for this method (required).
  repository: https://github.com/saeyslab/CytoNorm

argument_groups:
  - name: Parameters
    arguments:
      - type: integer
        name: --som_grid_size
        info:
          optimize:
            type: linear
            lower: 6
            upper: 16
        default: 15
        description: SOM grid size used when training CytoNorm model.
      - type: integer
        name: --num_metacluster
        info:
          optimize:
            type: linear
            lower: 8
            upper: 20
        default: 10
        description: Number of metaclusters generated when training CytoNorm model.
      - type: integer
        name: --n_quantiles 
        info:
          optimize:
            type: linear
            lower: 80
            upper: 120
        default: 99
        description: Number of quantiles to use when training the CytoNorm model. 

# Metadata for your component
# Resources required to run the component
resources:
  # The script of your component (required)
  - type: r_script
    path: script.R
  - path: /src/utils/anndata_to_fcs.R

engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: openproblems/base_r:1
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    setup:
      - type: python
        packages: [ anndata, h5py ]
      - type: r
        github: [saeyslab/cytoNorm]
        bioc: [ flowCore, Biobase ]
        packages: [ anndata, docstring ]

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
